name: Build SQPL

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: setup
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install libkrb5-dev -y
          sudo apt-get install -y libstdc++6
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16'
      - uses: actions/setup-python@v2
        with:
            python-version: '2.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax
      - run: |
            npm install --verbose --python=python2.7
      - name: Build
        run: |
            npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./output
          keep_files: true   